name: Deploy Static Web Page to Heroku




on:
  push:
    branches: [ main ]  # Runs on push to main and dev branches
  pull_request:
    branches: [ main]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm cache clean --force
    - run: npm ci


  deploy:
    needs: build  # This job runs after the build job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run deployment for main branch
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    # Install Heroku CLI (Fixes the "heroku not found" error)
    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh
    # Deploy to Heroku using CLI
    - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKUAPIKEY }}
        run: |
          heroku login --apikey=$HEROKU_API_KEY
          heroku git:remote -a greeno
          git push heroku main